---
title: 'Week1 HomeWork: RMarkDown Examples'
author: "Muharrem Çakır"
date: "October 15, 2018"
output:
  html_document:
    df_print: paged

---

## Who am I and what is my aim ? 

My name is Muharrem Çakır. I have been working as Data Management Consultant at Obase. 
I am participant as different roles like developer, Architect or Team Leader in our customers' projects. Our Customers are in various sectors like retail, banking, airlines, Telco , etc. 
İn our projects I responsible to service optimum solutions to our customers who have DWH , BI or analytics projects.

My aim is develop myself and help our customers especially about big data and analytic subjects.  

Below, I added 3 examples about R and how we can use it in Data Science projects in various sectors.

## Segmentation . How to perform k-means Clustering in R
Customer Segmentation is very important. İf you can do is successfuly, Yo can manage your campaign or you can do any other predictive models like churn, propensity successfully. 
In this video, you can find how to perfomr k-means clustering method in R. 

<a href="https://www.youtube.com/watch?v=sAtnX3UJyN0">Segmentation with k-means Clustering </a>


## Customer churn analysis
As thinking having a new customer is 10 times expensive than keeping  a existing customer , prediction to estimate who will leave is very important. We try to predict via a churn models. An example of Churn Modeling in R is below:


<a href="https://www.youtube.com/watch?v=adG-9Jk3QbQ">Data Science Demo - Customer Churn Analysis </a>


## Data manipulations
Data manipulation  is the most important step in data science Projects. it is observed in lots of projects that data manipalation step is equal %60-65 of all project time. Also it is very critical that if you don't do right things in this step your model's accuracy might be low.

Here is a good source about data manipulation:

<a href="https://www.youtube.com/watch?v=jWjqLW-u3hc">Hands-on dplyr tutorial for faster data manipulation in R </a>
